version: '3.7'

services:
  app:
    build: .
    container_name: 'pock-pdf-compress'
    command: chmod +x ./home/node/app/entrypoint.sh
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
